USE [master]
GO

/****** Object:  Database [Tennis]    Script Date: 07/27/2015 23:40:02 ******/
CREATE DATABASE [Tennis] ON  PRIMARY 
( NAME = N'Tennis_Data', FILENAME = N'D:\SolomiyaHnidets\Tennis.mdf' , SIZE = 5440KB , MAXSIZE = UNLIMITED, FILEGROWTH = 16384KB )
 LOG ON 
( NAME = N'Tennis_Log', FILENAME = N'D:\SolomiyaHnidets\Tennis_Log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 16384KB )
GO

ALTER DATABASE [Tennis] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Tennis].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Tennis] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Tennis] SET ANSI_NULLS ON 
GO

ALTER DATABASE [Tennis] SET ANSI_PADDING ON 
GO

ALTER DATABASE [Tennis] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [Tennis] SET ARITHABORT ON 
GO

ALTER DATABASE [Tennis] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Tennis] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Tennis] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Tennis] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Tennis] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Tennis] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Tennis] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [Tennis] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Tennis] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [Tennis] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Tennis] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Tennis] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Tennis] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Tennis] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Tennis] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Tennis] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Tennis] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Tennis] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Tennis] SET  READ_WRITE 
GO

ALTER DATABASE [Tennis] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Tennis] SET  MULTI_USER 
GO

ALTER DATABASE [Tennis] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Tennis] SET DB_CHAINING OFF 
GO


